### ISSUE TITLE
Mount command failed, returncode=32

### ISSUE THREAD

**Issue by jhiemer** [juliohm1978/kubernetes-cifs-volumedriver#1]
@juliohm1978 first of all thanks for the plugin. I am currently testing it and everything worked so far, except the final binding. My PV, PVC and POD files look as follows:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  flexVolume:
    driver: juliohm/cifs
    options:
      opts: sec=ntlm,uid=1000
      server: 10.244.0.7
      share: /volume
    secretRef:
      name: volume-secret
```

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

```yaml
---
kind: Pod
apiVersion: v1
metadata:
  name: volume-pod
spec:
  volumes:
    - name: volume-storage
      persistentVolumeClaim:
        claimName: sample-volume-claim
  containers:
    - name: volume-pod-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: volume-storage
```

When I mount the volume I get:
`MountVolume.SetUp failed for volume "sample-volume" : mount command failed, status: Failure, reason: Failed to mount 10.244.0.7:/volume at /var/lib/kubelet/pods/bebada2b-3695-11e8-a66c-0a0b5faee91b/volumes/juliohm~cifs/sample-volume returncode=32`

Going to the worker I can see the whole path except `sample-volume`. When I run the command manually and bind to `/var/lib/kubelet/pods/bebada2b-3695-11e8-a66c-0a0b5faee91b/volumes/juliohm~cifs` on the worker node, it is successful.

Am I missing something? Where is `sample-volume` coming from during POD creation? Shall it be created automatically?

**Comment by juliohm1978** [comment]
`/var/lib/kubelet/pods/bebada2b-3695-11e8-a66c-0a0b5faee91b/volumes/juliohm~cifs/sample-volume` should be created automatically.

`returncode=32` is the return code from the mount command, so that failed for some reason on the node the pod is running.

My first step to diagnose would be to try and mount the NFS share yourself on that node. If you have root or sudo access to the node, you can try

```bash
mount -t nfs -o sec=ntlm,uid=1000 10.244.0.7:/volume /mnt
```

... either `/mnt` or any other temporary directory you can use for testing.

If that doesn't work, it's a clear indication that something is not quite well configured with your NFS sharing.

Let me know if you keep having troubles.

**Comment by jhiemer** [comment]
@juliohm1978 ok, did a test. Went to the worker and executed:

`worker/271ea794-281a-4f6a-9ff8-999a8e7e316d:/var/vcap/bosh_ssh/bosh_17d36313e911434# sudo mount -t cifs -o username=bV4J5GCk8d,password=******** "//10.244.0.7/volume" /mnt`

Then:
```shell
cd /mnt/
worker/271ea794-281a-4f6a-9ff8-999a8e7e316d:/mnt# ls
worker/271ea794-281a-4f6a-9ff8-999a8e7e316d:/mnt# touch test.yml
```
And on the share:
```shell
samba/97bb6fcd-0e33-4c7b-bbec-8d28ae734743:/var/vcap/store/smbshare# ls
test.yml
```

**Comment by juliohm1978** [comment]
That's strange. The driver should be using pretty much the same mount command.

Can you post the yaml for `volume-secret`. Feel free to redact username and password. Just curious about the yaml structure.

**Comment by jhiemer** [comment]
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: volume-secret
type: juliohm/cifs
data:
  password: ****** # (base64 encoded pw)
  username: YlY0SjVHQ2s4ZA==
```
