### ISSUE TITLE
Cannot mount volume if driver.options.opts is empty

### ISSUE THREAD

**Issue by juliohm1978** [juliohm1978/kubernetes-cifs-volumedriver#3]
Found by @FerronN while discussing issue [#1](https://github.com/juliohm1978/kubernetes-cifs-volumedriver/issues/1#issuecomment-412158036), the driver fails when mount options are left empty.

The following, as a provided example, does not work:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mycifspv
spec:
  capacity:
    storage: 1Gi
  flexVolume:
    driver: juliohm/cifs
    options:
      server: my-cifs-host
      share: /MySharedDirectory
    secretRef:
      name: my-secret
```

... mainly because it does not define a value for `spec.flexVolume.options.opts`.

```yaml
apiVersion: v1
spec:
  flexVolume:
    options:
      opts: sec=ntlm,uid=1000
```

Internally, Json parsing from `jq` returns `null` instead of an empty string.
