### ISSUE TITLE
Mount fails 

### ISSUE THREAD

**Issue by rsteckler** [juliohm1978/kubernetes-cifs-volumedriver#6]
The following works great when executed on a node:
```
sudo mount -t cifs //192.168.2.12/Media /mnt/cifs -o username=guest,password=guest
```

From Kubernetes, I get the following:
```
MountVolume.SetUp failed for volume "jabba-media-volume" : invalid character '/' after object key:value pair
```

Here is my volume yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jabba-media-volume
spec:
  storageClassName: media
  capacity:
    storage: 10Ti
  flexVolume:
    driver: juliohm/cifs
    options:
      opts: sec=ntlm,uid=1000
      server: 192.168.2.12
      share: /Media
    secretRef:
      name: jabba-media-secret
  accessModes:
    - ReadWriteMany
```

Thanks for any help you can provide!
